version: "1.0"
projectName: IT_MC_DemoDADA1Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: fld_113520462_stage00.projects.fla3d2851d02a5eb26510139.integrations:DummyTest
    type: flow
    stepId: /0
    reference: fld_113520462_stage00.projects.fla3d2851d02a5eb26510139.WmPackageServiceProvider.wmx.mc.utils.is:getSysInfoData
- runtimeAlias: IT_MC_VRT1
  assets:
  - name: DemoEdgeBasedQueryingDB
    type: workflow
    uid: fl2a3902aab595d8450b44a8
    stepId: a0
    reference: MCDemoSQLCloud.flow:getRegulatoryReportList
  - name: DemoEdgeBasedQueryingDB
    type: workflow
    uid: fl2a3902aab595d8450b44a8
    stepId: a3
    reference: project.it_mc_demodada1.integrations:getRegulatoryReportDAF
  - name: WF_HelloWorld
    type: workflow
    uid: fl0f8324ab0524393085629c
    stepId: a0
    reference: MCHelloWorld.flow:helloWorld
